matrix:
  include:
    - language: java
      before_install:
        - chmod +x gradlew
      script:
        - ./gradlew build
      deploy:
        provider: heroku
        api_key: 5e506f90-473b-4ede-8be2-1d11b1f5c4da
        app: repairshop-backend-ecse321-09
        on:
          branch:
            main